In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import operator
import random
import time
import numpy as np
from sklearn.preprocessing import MinMaxScaler




In [2]:
T1 = time.time()

def knn(x_test, x_data, y_data, k):
    # 计算样本数量
    x_data_size = x_data.shape[0]
    # 复制x_test
    np.tile(x_test, (x_data_size, 1))
    # 计算x_test与每一个样本的差值
    diffMat = np.tile(x_test, (x_data_size, 1)) - x_data
    # 计算差值的平方
    sqDiffMat = diffMat ** 2
    # 求和
    sqDistances = sqDiffMat.sum(axis=1)
    # 开方
    distances = sqDistances ** 0.5
    # 从小到大排序,注意argsort返回的是坐标不是列表！！！
    sortedDistances = distances.argsort()
    # print("--------------")
    # print(sortedDistances)
    #------------改进部分-------
    # 求权
    distancesByWeight = inverse(distances, 4,1)

    classCount = {}
    for i in range(k):
        # 获取标签
        votelabel = y_data[sortedDistances[i]]
        #print(votelabel)
        #print(distances[sortedDistances[i]])
        print(distancesByWeight[sortedDistances[i]])

        # 统计标签数量
        classCount[votelabel] = classCount.get(votelabel, 0) + distancesByWeight[sortedDistances[i]] * 1
    # 根据operator.itemgetter(1)-第1个值对classCount排序，然后再取倒序
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    # 获取数量最多的标签
    return sortedClassCount[0][0]

 #------------改进部分-------
def inverse(dist,a, b):
    """ Input a distance and return it`s weight"""
    weight = 1 / (a*dist + b)
    return weight

In [3]:
# 载入数据
iris = datasets.load_iris()


mm = MinMaxScaler(feature_range=(0, 1))
iris.data = mm.fit_transform(iris.data)

x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size=0.2,random_state=2) #分割数据0.2为测试数据，0.8为训练数据




# #打乱数据
# data_size = iris.data.shape[0]
# index = [i for i in range(data_size)]
# random.shuffle(index)
# iris.data = iris.data[index]
# iris.target = iris.target[index]
#
# #切分数据集
# test_size = 40
# x_train = iris.data[test_size:]
# x_test = iris.data[:test_size]
# y_train = iris.target[test_size:]
# y_test = iris.target[:test_size]

In [4]:
predictions = []
for i in range(x_test.shape[0]):
    predictions.append(knn(x_test[i], x_train, y_train, 5))
    print("------------")


print(classification_report(y_test, predictions))

0.7638805587678321
0.728502972096815
0.6845084486936264
0.675911275951832
0.6759112759518319
------------
0.8475091939564026
0.8114683069327147
0.7638805587678328
0.7499999999999997
0.7285029720968146
------------
0.7169721636844375
0.7169721636844375
0.6593416627638973
0.5927034866470544
0.5496600113870036
------------
0.8331192187834345
0.8254430244809361
0.7878644846835418
0.7862122981409709
0.6973973605843355
------------
0.8309859154929579
0.7404081963766923
0.6994411140063052
0.6952855865173595
0.6899931655322857
------------
0.6596778043900791
0.5980123543619501
0.5766520076219934
0.5424648790780928
0.5346744496457804
------------
0.8508442995363131
0.8254430244809364
0.787864484683542
0.7826086956521741
0.6587357603069818
------------
0.62341131304344
0.5811427822265464
0.5516858210574259
0.5478863011840278
0.53019119116891
------------
0.8571428571428572
0.7082907437139454
0.7019681646326585
0.6783771924332177
0.6499283701435309
------------
0.8331192187834345
0.78786448468354

In [5]:
print(confusion_matrix(y_test, predictions))

T2 = time.time()
print('程序运行时间:%s秒' % ((T2 - T1)))


[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
程序运行时间:0.09373021125793457秒
