In [1]:
# 导入算法包以及数据集
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import operator
import random
import time

In [2]:
T1 = time.time()

def knn(x_test, x_data, y_data, k):
    # 计算样本数量
    x_data_size = x_data.shape[0]
    # 复制x_test
    np.tile(x_test, (x_data_size, 1))
    # 计算x_test与每一个样本的差值
    diffMat = np.tile(x_test, (x_data_size, 1)) - x_data
    # 计算差值的平方
    sqDiffMat = diffMat ** 2
    # 求和
    sqDistances = sqDiffMat.sum(axis=1)
    # 开方
    distances = sqDistances ** 0.5
    # 从小到大排序
    sortedDistances = distances.argsort()
    print(sortedDistances)
    # 求权
    distancesByWeight = gaussian(distances)

    classCount = {}
    for i in range(k):
        # 获取标签
        votelabel = y_data[sortedDistances[i]]
        print(distancesByWeight[sortedDistances[i]])
        # 统计标签数量
        classCount[votelabel] = classCount.get(votelabel, 0) + distancesByWeight[sortedDistances[i]] * 1
    # 根据operator.itemgetter(1)-第1个值对classCount排序，然后再取倒序
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    # 获取数量最多的标签
    return sortedClassCount[0][0]

In [3]:
def gaussian(dist, sigma=10.0):
    """ Input a distance and return it`s weight"""
    weight = np.exp(-dist ** 2 / (2 * sigma ** 2))
    return weight

In [4]:
# 载入数据
iris = datasets.load_iris()
x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size=0.2) #分割数据0.2为测试数据，0.8为训练数据

#打乱数据
# data_size = iris.data.shape[0]
# index = [i for i in range(data_size)]
# random.shuffle(index)
# iris.data = iris.data[index]
# iris.target = iris.target[index]

#切分数据集
# test_size = 40
# x_train = iris.data[test_size:]
# x_test = iris.data[:test_size]
# y_train = iris.target[test_size:]
# y_test = iris.target[:test_size]

predictions = []
for i in range(x_test.shape[0]):
    predictions.append(knn(x_test[i], x_train, y_train, 5))
    print("------------")

print(classification_report(y_test, predictions))

[119   4 118  10  40  16  95   9  22  58  79  81 114 100  14  84  13 105
  77  36  74   6  69  32  51  88  56  48  65  47  17  82  39  59  87  76
  50  98  24  96  57  31  93  71  73  18  33  97  54 109  70  67  92   3
 111  94 103  34  46 113  15  28 112  23  44  99  35  29  78  38  43 104
 101  89  75  21  49 108   1  20  85  86 110  63  66 116  53   7  55  37
  25   0 102 107  42  41  12  91  52  80   2  83  11  30  64 115  61  60
  72  27  19  90   8  45  26 106  68  62   5 117]
1.8824098475949752e-30
0.00033546262790251185
0.8824969025845955
2.804404738222797e-14
8.808179196460557e-08
------------
[ 58  79   4 118  40 100 119 114  81  95  13  22  10  14  74   9  77  56
  16  32  48  51  36  47  69  82  59  65  76  87  96  39  24  17  50  98
  57  73  71  93  31  84  33   6 105  18  88  97  54  70  92 109 111   3
  94  67  34 103  46 113  15  28  23 112  44  99  35  29  38  43  75  21
  89   1  20  37  78 104 101  60  49  90  85 110 108  63  55   0  66 102
  86  45  25  91 116  41 

In [5]:
print(confusion_matrix(y_test, predictions))

[[14  0  0]
 [ 0  8  0]
 [ 0  3  5]]


In [6]:
T2 = time.time()
print('程序运行时间:%s秒' % ((T2 - T1)))

程序运行时间:0.07496309280395508秒
