In [1]:
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
import operator
import random
import os
import sys
import time
from tensorflow import keras

In [2]:
T1 = time.time()

In [3]:
# fashion_mnist图像分类数据集
fashion_mnist = keras.datasets.fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

y_test=y_test.flatten()
x_train=x_train.reshape(60000,784)
y_train=y_train.flatten()
x_test=x_test.reshape(10000,784)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

4431872/4422102 [==============================] - 0s 0us/step
(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [4]:
def knn(x_test, x_data, y_data, k):
    # 计算样本数量
    x_data_size = x_data.shape[0]
    # 复制x_test
    np.tile(x_test, (x_data_size, 1))
    # 计算x_test与每一个样本的差值
    diffMat = np.tile(x_test, (x_data_size, 1)) - x_data
    # 计算差值的平方
    sqDiffMat = diffMat ** 2
    # 求和
    sqDistances = sqDiffMat.sum(axis=1)
    # 开方
    distances = sqDistances ** 0.5
    # 从小到大排序
    sortedDistances = distances.argsort()

    classCount = {}
    for i in range(k):
        # 获取标签
        votelabel = y_data[sortedDistances[i]]
        # 统计标签数量
        classCount[votelabel] = classCount.get(votelabel, 0) + 1
    # 根据operator.itemgetter(1)-第1个值对classCount排序，然后再取倒序
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    # 获取数量最多的标签
    return sortedClassCount[0][0]

In [5]:
predictions = []
for i in range(x_test.shape[0]):
    predictions.append(knn(x_test[i], x_train, y_train, 5))

print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.66      0.80      0.73      1000
           1       0.84      0.96      0.89      1000
           2       0.64      0.69      0.66      1000
           3       0.69      0.85      0.76      1000
           4       0.70      0.54      0.61      1000
           5       0.68      0.96      0.80      1000
           6       0.63      0.35      0.45      1000
           7       0.84      0.75      0.80      1000
           8       0.95      0.75      0.84      1000
           9       0.92      0.86      0.89      1000

    accuracy                           0.75     10000
   macro avg       0.76      0.75      0.74     10000
weighted avg       0.76      0.75      0.74     10000



In [6]:
print(confusion_matrix(y_test, predictions))

[[799  25   6 107   2   7  41   1  12   0]
 [  2 956   4  26   3   3   5   0   1   0]
 [ 82   9 685  39 101  18  62   1   3   0]
 [ 37  77   2 846  16   3  11   0   8   0]
 [ 29  31 214  90 535  14  80   0   7   0]
 [  0   2   0   2   0 964   0  24   0   8]
 [237  36 137 106  99  18 354   2   9   2]
 [  0   0   0   0   0 201   0 752   0  47]
 [ 16   3  17   7  10 105   6  63 751  22]
 [  0   0   0   5   0  82   0  48   0 865]]


In [7]:
T2 = time.time()
print('程序运行时间:%s秒' % ((T2 - T1)))

程序运行时间:1085.864955663681秒
