In [1]:
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
import operator
import random
import os
import sys
import time
from tensorflow import keras


In [2]:
T1 = time.time()

In [3]:
def knn(x_test, x_data, y_data, k):
    # 计算样本数量
    x_data_size = x_data.shape[0]
    # 复制x_test
    np.tile(x_test, (x_data_size, 1))
    # 计算x_test与每一个样本的差值
    diffMat = np.tile(x_test, (x_data_size, 1)) - x_data
    # 计算差值的平方
    sqDiffMat = diffMat ** 2
    # 求和
    sqDistances = sqDiffMat.sum(axis=1)
    # 开方
    distances = sqDistances ** 0.5
    # 从小到大排序
    sortedDistances = distances.argsort()

    classCount = {}
    for i in range(k):
        # 获取标签
        votelabel = y_data[sortedDistances[i]]
        # 统计标签数量
        classCount[votelabel] = classCount.get(votelabel, 0) + 1
    # 根据operator.itemgetter(1)-第1个值对classCount排序，然后再取倒序
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    # 获取数量最多的标签
    return sortedClassCount[0][0]

In [4]:
(x_train,y_train),(x_test,y_test) = keras.datasets.cifar10.load_data()
#x_train,x_test,y_train,y_test = train_test_split(cifar10.data, cifar10.target, test_size=0.2)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

y_test=y_test.flatten()
x_train=x_train.reshape(50000,3072)
y_train=y_train.flatten()
x_test=x_test.reshape(10000,3072)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

170508288/170498071 [==============================] - 6s 0us/step
(50000, 32, 32, 3)
(50000, 1)
(10000, 32, 32, 3)
(10000, 1)
(50000, 3072)
(50000,)
(10000, 3072)
(10000,)


In [5]:

predictions = []
for i in range(x_test.shape[0]):
    predictions.append(knn(x_test[i], x_train, y_train, 9))

print(classification_report(y_test, predictions))


              precision    recall  f1-score   support

           0       0.17      0.66      0.26      1000
           1       0.38      0.19      0.25      1000
           2       0.18      0.34      0.24      1000
           3       0.29      0.13      0.18      1000
           4       0.32      0.15      0.20      1000
           5       0.31      0.09      0.14      1000
           6       0.34      0.14      0.20      1000
           7       0.41      0.11      0.18      1000
           8       0.30      0.45      0.36      1000
           9       0.44      0.13      0.20      1000

    accuracy                           0.24     10000
   macro avg       0.31      0.24      0.22     10000
weighted avg       0.31      0.24      0.22     10000



In [6]:
print(confusion_matrix(y_test, predictions))

[[657  20 107  11  11   5  13   3 164   9]
 [391 188 100  30  18  17  26  25 152  53]
 [408  20 341  35  47  19  40  12  72   6]
 [327  31 222 134  38  53  63  26  86  20]
 [401   5 258  25 149  20  30  25  82   5]
 [358  20 229  81  40  92  52  24  87  17]
 [281  25 290  53  78  43 141  25  56   8]
 [374  33 166  37  64  24  28 111 139  24]
 [387  23  73  20   9   5   8   9 450  16]
 [377 136  68  29  19  18  10   8 209 126]]


In [7]:
T2 = time.time()
print('程序运行时间:%s秒' % ((T2 - T1)))

程序运行时间:3553.78897690773秒
