In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import operator
import random
import time
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction import DictVectorizer
from sklearn.decomposition import PCA



In [2]:
T1 = time.time()

def knn(x_test, x_data, y_data, k):
    # 计算样本数量
    x_data_size = x_data.shape[0]
    # 复制x_test
    np.tile(x_test, (x_data_size, 1))
    # 计算x_test与每一个样本的差值
    diffMat = np.tile(x_test, (x_data_size, 1)) - x_data
    # 计算差值的平方
    sqDiffMat = diffMat ** 2
    # 求和
    sqDistances = sqDiffMat.sum(axis=1)
    # 开方
    distances = sqDistances ** 0.5
    # 从小到大排序
    sortedDistances = distances.argsort()

    classCount = {}
    for i in range(k):
        # 获取标签
        votelabel = y_data[sortedDistances[i]]
        # 统计标签数量
        classCount[votelabel] = classCount.get(votelabel, 0) + 1
    # 根据operator.itemgetter(1)-第1个值对classCount排序，然后再取倒序
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    # 获取数量最多的标签
    return sortedClassCount[0][0]

In [3]:
# 载入数据
iris = datasets.load_iris()
mm = MinMaxScaler(feature_range=(0, 1))
iris.data=mm.fit_transform(iris.data)
print(type(iris.data))
x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size=0.2,random_state=2) #分割数据0.2为测试数据，0.8为训练数据


print(x_train.shape)
print(x_test.shape)



# #打乱数据
# data_size = iris.data.shape[0]
# index = [i for i in range(data_size)]
# random.shuffle(index)
# iris.data = iris.data[index]
# iris.target = iris.target[index]
#
# #切分数据集
# test_size = 40
# x_train = iris.data[test_size:]
# x_test = iris.data[:test_size]
# y_train = iris.target[test_size:]
# y_test = iris.target[:test_size]

<class 'numpy.ndarray'>
(120, 4)
(30, 4)


In [4]:
predictions = []
for i in range(x_test.shape[0]):
    predictions.append(knn(x_test[i], x_train, y_train, 5))

print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30



In [5]:
print(confusion_matrix(y_test, predictions))

T2 = time.time()
print('程序运行时间:%s秒' % ((T2 - T1)))

[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
程序运行时间:0.04713702201843262秒
