In [54]:
# 导入算法包以及数据集
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
import operator
import random
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
#cifar10_dir = './cifar-10-batches-py'

In [55]:
T1 = time.time()

def knn(x_test, x_data, y_data, k):
    # 计算样本数量
    x_data_size = x_data.shape[0]
    # 复制x_test
    np.tile(x_test, (x_data_size,1))
    # 计算x_test与每一个样本的差值
    diffMat = np.tile(x_test, (x_data_size,1)) - x_data
    # 计算差值的平方
    sqDiffMat = diffMat**2
    # 求和
    sqDistances = sqDiffMat.sum(axis=1)
    # 开方
    distances = sqDistances**0.5
    # 从小到大排序
    sortedDistances = distances.argsort()
    classCount = {}
    for i in range(k):
        # 获取标签
        votelabel = y_data[sortedDistances[i]]
        # 统计标签数量
        classCount[votelabel] = classCount.get(votelabel,0) + 1
    # 根据operator.itemgetter(1)-第1个值对classCount排序，然后再取倒序
    sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1), reverse=True)
    # 获取数量最多的标签
    return sortedClassCount[0][0]

In [56]:
hand=datasets.load_digits()
print(hand.data.shape)
x_train,x_test,y_train,y_test = train_test_split(hand.data, hand.target, test_size=0.2,random_state=1)
print(x_train.shape)
print(y_train.shape)
print(y_train)
print(x_test.shape)
print(x_test)
mm = MinMaxScaler(feature_range=(0, 1))
x_train = mm.fit_transform(x_train)
x_test=mm.fit_transform(x_test)
print(x_test)

(1797, 64)
(1437, 64)
(1437,)
[4 9 6 ... 9 1 5]
(360, 64)
[[ 0.  0.  6. ...  3.  0.  0.]
 [ 0.  8. 13. ...  0.  0.  0.]
 [ 0.  0.  4. ...  6.  0.  0.]
 ...
 [ 0.  0.  0. ...  1.  0.  0.]
 [ 0.  3. 15. ... 16. 16.  2.]
 [ 0.  0.  8. ...  0.  0.  0.]]


In [57]:
predictions = []
for i in range(x_test.shape[0]):
    predictions.append(knn(x_test[i], x_train, y_train, 5))

print(classification_report(y_test, predictions))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        43
           1       1.00      1.00      1.00        35
           2       1.00      0.97      0.99        36
           3       1.00      1.00      1.00        41
           4       1.00      1.00      1.00        38
           5       1.00      1.00      1.00        30
           6       1.00      1.00      1.00        37
           7       0.97      0.97      0.97        37
           8       1.00      1.00      1.00        29
           9       0.97      1.00      0.99        34

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360



In [58]:
print(confusion_matrix(y_test,predictions))


T2 = time.time()
print('程序运行时间:%s秒' % ((T2 - T1)))

[[43  0  0  0  0  0  0  0  0  0]
 [ 0 35  0  0  0  0  0  0  0  0]
 [ 0  0 35  0  0  0  0  1  0  0]
 [ 0  0  0 41  0  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0]
 [ 0  0  0  0  0 30  0  0  0  0]
 [ 0  0  0  0  0  0 37  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  1]
 [ 0  0  0  0  0  0  0  0 29  0]
 [ 0  0  0  0  0  0  0  0  0 34]]
程序运行时间:0.21196722984313965秒
